site_name: Jujutsu docs
site_dir:  'rendered-docs'
# Not having this (or viewing the site locally, or from any place other than the
# site_url) leads to version switching failing to preserve the current path.
site_url: !ENV [SITE_URL_FOR_MKDOCS, 'https://martinvonz.github.io/jj/']
theme:
  name: 'material'
  language: 'en'
  features:
    # - navigation.top
extra:
  version:
    provider: mike
plugins:
    - offline
    - search

# Not all of these may be necessary, especially since the material
# theme substitutes for some of them
markdown_extensions:
  - toc:
      permalink: true
  - extra
  - sane_lists
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# This lists all the files that become part of the documentation
nav:
 - 'Older `jj` docs': 'index.md'

